## Mudumba Hanumat Krishna Vignesh
## Assignment 1

create database airlines;
use airlines;
select * from customer;
select * from passengers_on_flights;
select * from routes;
select * from ticket_details;

## 1. retrieve the details of customers who have booked more than one ticket.
select * from customer where customer_id in (select customer_id from ticket_details group by customer_id having sum(no_of_tickets) > 1);

## 2. find the customers who traveled on the most expensive ticket.
select * from customer where customer_id in (select customer_id from ticket_details where price_per_ticket = (select max(price_per_ticket) from ticket_details));

## 3. list all flights where the departure and arrival airports are different.
select * from routes where origin_airport != destination_airport;

## 4. find the customers who traveled the longest distance in a single flight.
select * from customer where customer_id in (select customer_id from passengers_on_flights where route_id in ( select route_id from routes
        where distance_miles = (select max(distance_miles) from routes)));

## 5. identify customers who have booked a ticket but have never traveled.
select * from customer where customer_id in (select customer_id from ticket_details where customer_id not in 
		(select distinct customer_id from passengers_on_flights));

## 6. find the top 3 most frequently traveled routes based on the number of passengers.
select r.route_id, r.origin_airport, r.destination_airport, count(p.customer_id) as passenger_count from passengers_on_flights p
join routes r on p.route_id = r.route_id group by r.route_id, r.origin_airport, r.destination_airport order by passenger_count desc limit 3;

## 7. find the average ticket price per travel class, including only those above $300.
select class_id, avg(price_per_ticket) as avg_price from ticket_details group by class_id having avg_price > 300;

## 8. calculate the total revenue generated by each airline brand.
select brand, sum(price_per_ticket * no_of_tickets) as total_revenue from ticket_details group by brand;
 
## 9. find the month with the highest number of tickets sold.
select extract(month from (str_to_date(p_date, '%Y-%m-%d'))) as p_month, count(*) as tickets_sold from ticket_details group by p_month order by tickets_sold desc limit 1;

## 10. retrieve the top 5 airports with the highest number of departures.
select origin_airport, count(*) as departure_count from routes group by origin_airport order by departure_count desc limit 5;

## 11. retrieve the details of flights along with the names of customers who traveled on them.
select p.flight_num, r.route_id, r.aircraft_id, c.first_name, c.last_name from passengers_on_flights p join routes r on p.route_id = r.route_id
join customer c on p.customer_id = c.customer_id;

## 12. find the most frequently used aircraft type for each travel class.
select class_id, aircraft_id, count(*) as maxcount from passengers_on_flights group by class_id, aircraft_id order by class_id, maxcount desc;

## 13. list the customers who have traveled on more than one airline brand.
select c.customer_id, c.first_name, c.last_name from customer c join ticket_details t on c.customer_id = t.customer_id group by c.customer_id, c.first_name, c.last_name
having count(distinct t.brand) > 1;

## 14. retrieve the total revenue generated from each customer.
select c.customer_id, c.first_name, c.last_name, sum(t.price_per_ticket * t.no_of_tickets) as total_spent from customer c join ticket_details t 
on c.customer_id = t.customer_id group by c.customer_id, c.first_name, c.last_name;

## 15. find the percentage of economy class tickets compared to the total tickets sold.
select (sum(case when class_id = 'economy' then no_of_tickets else 0 end) * 100.0 / sum(no_of_tickets)) as economy_percentage from ticket_details;

## 16. extract the first letter of each customer's first and last name and concatenate them as initials.
select customer_id, concat(left(first_name, 1), left(last_name, 1)) as initials from customer;

## 17. find all customers whose last names start with ‘s’ and traveled in ‘business’ class.
select c.customer_id,c.first_name,c.last_name from customer c join passengers_on_flights p on c.customer_id = p.customer_id where c.last_name like 's%' and p.class_id = 'business';

## 18. convert all origin and destination airport names to lowercase.
select lower(origin_airport) as origin_airport, lower(destination_airport) as destination_airport from routes;

## 19. calculate the total number of flights operated per day for the last 6 months.
select str_to_date(travel_date, '%Y-%m-%d') as travel_date, count(*) as total_flights from passengers_on_flights
where str_to_date(travel_date, '%Y-%m-%d') >= date_sub(current_date, interval 6 month) group by travel_date order by travel_date;

## 20. find the difference in days between the ticket purchase date and the travel date for each booking.
select p.customer_id, p.travel_date, t.p_date, timestampdiff(day, str_to_date(t.p_date, '%d-%m-%y'), str_to_date(p.travel_date, '%d-%m-%y')) as days_difference
from passengers_on_flights p join ticket_details t on p.customer_id = t.customer_id;
